In [17]:
# !pip install numpy

Section A: Basic Operations

In [2]:
import numpy as np

1. Import the NumPy library and create a 1D array of integers from 1 to 10.

In [69]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Create a 3x3 matrix filled with random numbers between 0 and 1.

In [5]:
matrix = np.random.rand(3, 3)
matrix

array([[0.70212525, 0.70148246, 0.41217189],
       [0.11160911, 0.93508497, 0.67892578],
       [0.48986516, 0.9055983 , 0.60475276]])

3. Create a 5x5 identity matrix using NumPy.

In [6]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


4. Generate an array of 20 linearly spaced numbers between 0 and 50.

In [58]:
numbers = np.linspace(0, 50, 20)
print(numbers)

[ 0.          2.63157895  5.26315789  7.89473684 10.52631579 13.15789474
 15.78947368 18.42105263 21.05263158 23.68421053 26.31578947 28.94736842
 31.57894737 34.21052632 36.84210526 39.47368421 42.10526316 44.73684211
 47.36842105 50.        ]


5. Convert a Python list [[1,2,3], [4,5,6], [7,8,9]] into a NumPy array and print
its type.

In [62]:
list = [[1,2,3], [4,5,6], [7,8,9]]
np_array = np.array(list)
print(type(np_array))

<class 'numpy.ndarray'>


Section B: Indexing & Slicing

6. Given the NumPy array arr = np.arange(10, 100, 10), extract elements from
index 2 to 5.


Extract the third column from the following matrix:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [64]:
arr = np.arange(10, 100, 10)
elements = arr[2:5]
print(elements)

[30 40 50]


In [8]:
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
third_column = matrix[:, 2]
print(third_column)

[30 60 90]


7. Replace all even numbers in an array with -1 (without using a loop).

In [10]:
arr = np.array([1, 2, 3, 4, 5,6,7,8,9])
result = np.where(arr % 2 == 0, -1, arr)
print(result)

[ 1 -1  3 -1  5 -1  7 -1  9]


Section C: Mathematical & Statistical Operations

9. Given arr = np.array([5, 10, 15, 20, 25]), compute:
 - Mean
 - Standard deviation
 - Sum of all elements
 
 - Hint: can use function np.mean(), np.std(), np.sum()


In [19]:
arr = np.array([5, 10, 15, 20, 25])
print(arr)
Mean = np.mean(arr)
print(Mean)
Standard_deviation = np.std(arr)
print(Standard_deviation)
Sum_of_all_elements = np.sum(arr)
print(Sum_of_all_elements)

[ 5 10 15 20 25]
15.0
7.0710678118654755
75


10. Create a 4x4 matrix with random integers between 1 and 100, and find:
- Maximum and Minimum value
- Row-wise sum

In [27]:
matrix = [[np.random.randint(1, 100) for _ in range(4)] for _ in range(4)]
print(matrix)
Maximum = max(max(matrix))
Minimum = min(min(matrix))
print("Max value in the matrix :",Maximum)
print("Min value in the matrix :",Minimum)
Row_wise = [sum(matrix[0]), sum(matrix[1]), sum(matrix[2]), sum(matrix[3])]
print("Row-wise sum in the matrix :",Row_wise)


[[4, 90, 28, 36], [78, 11, 28, 28], [85, 3, 89, 4], [66, 42, 82, 12]]
Max value in the matrix : 89
Min value in the matrix : 4
Row-wise sum in the matrix : [158, 145, 181, 202]


Section D: Advanced NumPy Functions

11. Create two (3x3) matrices filled with random integers and perform:
- Element-wise addition
- Matrix multiplication
Hint: For matrix multiplication, you can use numpy.dot()

In [33]:
matrix1 = np.random.randint(1, 10, size=(3, 3))
matrix2 = np.random.randint(1, 10, size=(3, 3))

print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

result = matrix1 + matrix2
print("\nElement-wise addition:")
print(result)

product = np.dot(matrix1, matrix2)
print("\nMatrix multiplication:")
print(product)

Matrix 1:
[[2 2 1]
 [7 6 3]
 [9 1 2]]
Matrix 2:
[[6 2 3]
 [3 3 7]
 [8 9 6]]

Element-wise addition:
[[ 8  4  4]
 [10  9 10]
 [17 10  8]]

Matrix multiplication:
[[26 19 26]
 [84 59 81]
 [73 39 46]]


12. [Optional] Given arr = np.array([1, 2, 3, np.nan, 5, 6, np.nan]),
remove all NaN values.
(kindly explore the topic np.nan by yourself, and try to solve the problem.)

In [35]:
arr = np.array([1, 2, 3, np.nan, 5, 6, np.nan])
print(arr)
clean_arr = arr[~np.isnan(arr)]
print(clean_arr)

[ 1.  2.  3. nan  5.  6. nan]
[1. 2. 3. 5. 6.]
